git:
  commitMessage: "release v${version}"
  tagName: "v${version}"
npm:
  publish: true
github:
  release: true
hooks:
  before:init:
    - yarn lint
    - yarn format
    - yarn typecheck
    - yarn clean
    - yarn build
